export const tokens = {
	TYPE: /number|boolean/,
	EXPORT: 'export',
	IMPORT: 'import',
	FROM: 'from',
	TRUE: 'true',
	FALSE: 'false',
	CONST: 'const',
	IF: 'if',
	ELSE: 'else',
	WHILE: 'while',
	FORK: 'fork', //FORより前に
	FOR: 'for',
	FUNCTION: 'function',
	RETURN: 'return',
	LET: 'let',
	PRINT: 'print',
	MOVE: 'move',
	FIRE: 'fire',
	RANDOM: 'random',
	MODULE: '@module',
	MAIN: '@main',
	//COMMENT: { match: /\/\/[^\n]*$/, lineBrakes: true},
	COMMENT: { match: /\/\/.*/, lineBrakes: true},
	EQUAL: '==',
	NOT_EQUAL: '!=',
	LESS_THAN_EQUAL: '<=',
	LESS_THAN: '<',
	GREATER_THAN_EQUAL: '>=',
	GREATER_THAN: '>',
	ASSIGN: '=',
	ADD: '+',
	SUB: '-',
	MUL: '*',
	DIV: '/',
	MOD: '%',
	NOT: '!',
	AND: '&&',
	OR: '||',
	LBRACE: '{',
	RBRACE: '}',
	LPAREN: '(',
	RPAREN: ')',
	LSQUARE: '[',
	RSQUARE: ']',
	COLON: ':',
	SEMICOLON: ';',
	COMMA: ',',
	INT: /[1-9][0-9]*/,
	REAL: /[+-]?[0-9]+(?:\.[0-9]+)?/,
	NAME: /[a-zA-Z_][a-zA-Z_0-9]*/,
	FILE_NAME: /"[^\n]+"/,
	WHITE_SPACE: /[ \t]+/,
	NEW_LINE: { match:/\n|\r/, lineBreaks: true}
};

