export const stageNames: string[] = [
    'Go straight',
    'Use sensor',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight',
    'Turn left',
    'Enemy',
    'Go straight'
];